puts "🌱 Seeding spices..."

Theater.create(name: "Seattle Downtown Multiplex", location: "100 Pike Street", number_of_screens: 10)
Theater.create(name: "Seattle Uptown Monoplex", location: "200 Stone Way", number_of_screens: 1)
Theater.create(name: "Regal 15", location: "1500 15th Street", number_of_screens: 8)
Theater.create(name: "AMC Madison Park", location: "2400 Madison Avenue", number_of_screens: 5)

Movie.create(name: "Spider-Man: No Way Home", opening_date: 2021, rating: "PG-13")
Movie.create(name: "The Lost Daughter", opening_date: 2021, rating: "R")
Movie.create(name: "Scream", opening_date: 2022, rating: "R")
Movie.create(name: "Compartment No. 6", opening_date: 2022, rating: "R")
Movie.create(name: "The Worst Person in the World", opening_date: 2022, rating: "R")
Movie.create(name: "Moonfall", opening_date: 2022, rating: "PG-13")
Movie.create(name: "Uncharted", opening_date: 2022, rating: "PG-13")
Movie.create(name: "Death on the Nile", opening_date: 2022, rating: "PG-13")
Movie.create(name: "Cyrano", opening_date: 2022, rating: "PG-13")
Movie.create(name: "The Batman", opening_date: 2022, rating: "PG-13")

Showing.create(movie_id: 1, theater_id: 1)
Showing.create(movie_id: 2, theater_id: 1)
Showing.create(movie_id: 3, theater_id: 1)
Showing.create(movie_id: 4, theater_id: 1)
Showing.create(movie_id: 5, theater_id: 1)
Showing.create(movie_id: 6, theater_id: 1)
Showing.create(movie_id: 7, theater_id: 1)
Showing.create(movie_id: 8, theater_id: 1)
Showing.create(movie_id: 9, theater_id: 1)
Showing.create(movie_id: 10, theater_id: 1)
Showing.create(movie_id: 5, theater_id: 2)
Showing.create(movie_id: 10, theater_id: 3)
Showing.create(movie_id: 9, theater_id: 3)
Showing.create(movie_id: 8, theater_id: 3)
Showing.create(movie_id: 7, theater_id: 3)
Showing.create(movie_id: 6, theater_id: 3)
Showing.create(movie_id: 5, theater_id: 3)
Showing.create(movie_id: 4, theater_id: 3)
Showing.create(movie_id: 3, theater_id: 3)
Showing.create(movie_id: 10, theater_id: 4)
Showing.create(movie_id: 9, theater_id: 4)
Showing.create(movie_id: 8, theater_id: 4)
Showing.create(movie_id: 7, theater_id: 4)
Showing.create(movie_id: 6, theater_id: 4)

puts "✅ Done seeding!"
